apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "valheim.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valheim.labels" . | nindent 4 }}
data:
  {{- range $i, $instance := .Values.instances }}
  {{- $prefix := printf "%s-%d" (include "valheim.fullname" $) $i }}
  {{- range $filename, $content := (include "valheim.playerLists" $instance | fromJson) }}
  {{ printf "%s.%s" $prefix $filename }}: {{ $content | quote }}
  {{- end }}
  {{ include "valheim.fullname" $ }}-{{ $i }}: |
  {{- range $key, $value := $instance }}
  {{- if not (has $key (list "password" "service" "preset" "modifiers" "setKeys" "adminList" "bannedList" "permittedList")) }}
    {{- if eq $key "crossPlay" }}
    {{- if $value }}
    {{ $key }}=-crossplay
    {{- else }}
    {{ $key }}=
    {{- end }}
    {{- else }}
    {{ $key }}={{ $value }}
    {{- end }}
    {{- end }}
  {{- end }}
    {{- $args := list }}
    {{- with $instance.preset }}
      {{- $args = append (append $args "-preset") . }}
    {{- end }}
    {{- range $modifier, $value := $instance.modifiers }}
      {{- $args = append (append (append $args "-modifier") $modifier) $value }}
    {{- end }}
    {{- range $instance.setKeys }}
      {{- $args = append (append $args "-setkey") . }}
    {{- end }}
    {{- if $args }}
    set -- "$@"{{ range $args }} {{ . | toString | replace "'" "'\"'\"'" | printf "'%s'" }}{{ end }}
    {{- end }}
  {{- end }}
