apiVersion: v1
kind: Service
metadata:
  name: {{ include "valheim.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "valheim.labels" . | nindent 4 }}
  {{- with .Values.headlessService.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.headlessService.type }}
  clusterIP: None
  ports:
    - name: server-port
      port: {{ .Values.valheimDedicatedServer.port }}
      targetPort: server-port
      protocol: UDP
    - name: query-port
      port: {{ add .Values.valheimDedicatedServer.port 1 }}
      targetPort: query-port
      protocol: UDP
  selector:
    {{- include "valheim.selectorLabels" . | nindent 4 }}
---
{{- range $i, $instance := .Values.instances }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valheim.fullname" $ }}-{{ $i }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "valheim.labels" $ | nindent 4 }}
    {{- with $instance.service.metadata.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $instance.service.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $instance.service.type }}
  {{- with $instance.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  ports:
    - name: server-port
      port: {{ $.Values.valheimDedicatedServer.port }}
      targetPort: server-port
      protocol: UDP
    - name: query-port
      port: {{ add $.Values.valheimDedicatedServer.port 1 }}
      targetPort: query-port
      protocol: UDP
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "valheim.fullname" $ }}-{{ $i }}
---
{{- end }}
